language: node_js
node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - "10.9"

addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4

cache:
  npm: true
  directories:
    - $HOME/.cache

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    - managed-list
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        # - npm run lint:hbs
        # - npm run lint:js
        - npm test
        - npm start && wait-on http://localhost:4200
        - cypress run

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - npm ci
      script:
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-3.13
    - env: EMBER_TRY_SCENARIO=ember-3.14
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
